"""Added carid

Revision ID: 64ce4f59ccd7
Revises: b04e063b1a39
Create Date: 2024-11-16 16:37:55.863198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ce4f59ccd7'
down_revision = 'b04e063b1a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carid', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.drop_column('carid')

    # ### end Alembic commands ###
