"""Initial migration

Revision ID: b04e063b1a39
Revises: 
Create Date: 2024-11-16 16:37:32.555084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b04e063b1a39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share',
    sa.Column('shortuuid', sa.Text(length=22), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('expiry', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('shortuuid'),
    sa.UniqueConstraint('shortuuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('share')
    # ### end Alembic commands ###
